### ISSUE TITLE
[Bug report] Distributed Job init failed.

### ISSUE THREAD

**Issue by siaimes** [microsoft/openpai-runtime#47]
```
protocolVersion: 2
name: siaimes
type: job
jobRetryCount: 0
prerequisites:
  - type: dockerimage
    uri: 'siaimes/pytorch1.10.0:v1.0.0'
    name: docker_image_0
taskRoles:
  taskrole:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 6
      memoryMB: 73994
    commands:
      - env
  taskrole_1:
    instances: 1
    completion:
      minFailedInstances: 1
    taskRetryCount: 0
    dockerImage: docker_image_0
    resourcePerInstance:
      gpu: 1
      cpu: 6
      memoryMB: 73994
    commands:
      - env
defaults:
  virtualCluster: k80
extras:
  com.microsoft.pai.runtimeplugin:
    - plugin: ssh
      parameters:
        jobssh: true
        userssh:
          type: custom
          value: ''
    - plugin: teamwise_storage
      parameters:
        storageConfigNames:
          - share
  hivedScheduler:
    taskRoles:
      taskrole:
        skuNum: 1
        skuType: gpu-machine-k80
      taskrole_1:
        skuNum: 1
        skuType: gpu-machine-k80
```

error log:
```
.......
+ CHILD_PROCESS=ERROR_SPEC
+ cp /usr/local/pai-config/runtime-exit-spec.yaml /usr/local/pai/runtime.d
+ CHILD_PROCESS=ENV_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genenv framework.json
2022-03-05 07:01:14,448 - INFO - framework_parser.py:196 - loading json from framework.json
2022-03-05 07:01:14,448 - INFO - framework_parser.py:107 - task roles: {'taskrole': {'number': 1, 'ports': {'schedulePortStart': 15000, 'schedulePortEnd': 40000, 'ports': {'ssh': {'count': 1}, 'http': {'count': 1}}}}, 'taskrole1': {'number': 1, 'ports': {'schedulePortStart': 15000, 'schedulePortEnd': 40000, 'ports': {'ssh': {'count': 1}, 'http': {'count': 1}}}}}
+ CHILD_PROCESS=CONFIG_GENERATOR
+ python /usr/local/pai/init.d/framework_parser.py genconf framework.json
2022-03-05 07:01:14,511 - INFO - framework_parser.py:196 - loading json from framework.json
+ CHILD_PROCESS=PLUGIN_INITIALIZER
+ python /usr/local/pai/init.d/initializer.py /usr/local/pai/runtime.d/job_config.yaml /usr/local/pai/secrets/secrets.yaml /usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml /usr/local/pai/token-secrets/token /usr/local/pai/plugins /usr/local/pai/runtime.d taskrole1
2022-03-05 07:01:14,595 - INFO - initializer.py:235 - loading yaml from /usr/local/pai/runtime.d/job_config.yaml
Traceback (most recent call last):
  File "/usr/local/pai/init.d/initializer.py", line 268, in <module>
    main()
  File "/usr/local/pai/init.d/initializer.py", line 253, in main
    args.runtime_path, args.task_role)
  File "/usr/local/pai/init.d/initializer.py", line 148, in init_plugins
    plugin_configs = collect_plugin_configs(jobconfig, taskrole)
  File "/usr/local/pai/init.d/initializer.py", line 102, in collect_plugin_configs
    if 'prerequisites' in jobconfig['taskRoles'][taskrole] and 'prerequisites' in jobconfig:
KeyError: 'taskrole1'
+ exit_handler
+ EXIT_CODE=1
+ '[[' 1 -eq 0 ]]
+ echo 'start execute exit handler'
start execute exit handler
+ echo 'child process is PLUGIN_INITIALIZER, exit code is 1'
child process is PLUGIN_INITIALIZER, exit code is 1
+ '[[' PLUGIN_INITIALIZER '=' FRAMEWORK_BARRIER ]]
+ '[[' PLUGIN_INITIALIZER '=' PORT_CONFLICT_CHECKER ]]
+ '[[' PLUGIN_INITIALIZER '=' DOCKER_IMAGE_CHECKER ]]
+ echo 'Unknown exit code, platform error'
Unknown exit code, platform error
+ exit 1
```

According to the error message, I changed `taskrole_1` to `taskrole1` and the job started normally.

Here `taskrole_1` is automatically generated by the front end, and `taskrole1` is what the back end thinks. There is an incompatibility here.

**Comment by siaimes** [comment]
I created a hotfix for this issue. To use the hotfix. Please run kubectl edit ds webportal-ds first,
Then change the `image: openpai/webportal:v1.8.0` to `image: siaimes/webportal:v1.8.0-hp1`

If you want to persist the configuration, please change this line and restart webportal service:

[        image: {{ cluster_cfg['cluster']['docker-registry']['prefix'] }}webportal:{{ cluster_cfg['cluster']['docker-registry']['tag'] }}](https://github.com/microsoft/pai/blob/02442f3569a6ec232e7f074423ffd61b22d37ddc/src/webportal/deploy/webportal.yaml.template#L36)
