### ISSUE TITLE
jinja2==2.11.3 conflict with newest markupsafe, which cause init tensorboard crash.

### ISSUE THREAD

**Issue by siaimes** [microsoft/openpai-runtime#49]
```
+ python /usr/local/pai/init.d/initializer.py /usr/local/pai/runtime.d/job_config.yaml /usr/local/pai/secrets/secrets.yaml /usr/local/pai/user-extension-secrets/userExtensionSecrets.yaml /usr/local/pai/token-secrets/token /usr/local/pai/plugins /usr/local/pai/runtime.d taskrole
2022-04-14 11:30:23,269 - INFO - initializer.py:235 - loading yaml from /usr/local/pai/runtime.d/job_config.yaml
2022-04-14 11:30:23,284 - INFO - initializer.py:173 - Starting to prepare plugin ssh
2022-04-14 11:30:23,466 - INFO - initializer.py:52 - 2022-04-14 11:30:23,466 - INFO - init.py:118 - Ssh runtime plugin perpared
2022-04-14 11:30:23,481 - INFO - initializer.py:173 - Starting to prepare plugin teamwise_storage
2022-04-14 11:30:23,933 - INFO - initializer.py:52 - This plugin is deprecated, will ignore this plugin
2022-04-14 11:30:24,071 - INFO - initializer.py:173 - Starting to prepare plugin tensorboard
2022-04-14 11:30:24,129 - INFO - initializer.py:52 - Traceback (most recent call last):
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - File "/usr/local/pai/plugins/tensorboard/init.py", line 23, in <module>
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - from jinja2 import Template
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - from .environment import Environment
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - from .defaults import BLOCK_END_STRING
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - from markupsafe import soft_unicode
2022-04-14 11:30:24,130 - INFO - initializer.py:52 - ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
2022-04-14 11:30:24,135 - ERROR - initializer.py:56 - failed to run /usr/local/pai/plugins/tensorboard/init.py, error code is 1
```

**Comment by siaimes** [comment]
I created a hotfix for this issue. To use the hotfix. Please run kubectl edit ds rest-server-ds first,
Then change the env LAUNCHER_RUNTIME_IMAGE to `siaimes/openpai-runtime:v0.1.12-hp3`

```
- name: LAUNCHER_RUNTIME_IMAGE
  value: siaimes/openpai-runtime:v0.1.12-hp3
```

If you want to persist the configuration, please follow this:

https://github.com/microsoft/openpai-runtime/issues/33#issuecomment-730818664
